apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: bigquerydataset
spec:
  defaultTableExpirationMs: 36000000
  location: us-west1
---
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  labels:
    data-source: external
    schema-type: auto-junk
  name: bigquerytable
spec:
  datasetRef:
    external: bigquerydataset
